owner: lucas-dev31140
repo: elsitesstatus

sites:
  - name: Site principal
    url: https://elsites.fr
  - name: Espace client
    url: https://client.elsites.fr
  - name: Serveur web
    url: https://web.elsites.fr

status-website:
  cname: status.elsites.fr
  locale: fr
  logoUrl: https://elsites.fr/logo.png
  name: ELsites – Uptime
  introTitle: "**Status ELsites — Statut en temps réel**"
  introMessage: "Suivi en temps réel de la disponibilité de tous les services ELsites."
  navbar:
    - title: Statut
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO


